#!/usr/bin/env python3
import sys
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

flask_path = _PROGRAM_DIR / "frontend.py"

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)

#flask_proc = subprocess.Popen([context.env_exe, str(flask_path)])

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
